/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class AccessRequestSpecification implements AxdrType {

    public byte[] code = null;

    public static enum Choices {
        _ERR_NONE_SELECTED(-1),
        ACCESS_REQUEST_GET(1),
        ACCESS_REQUEST_SET(2),
        ACCESS_REQUEST_ACTION(3),
        ACCESS_REQUEST_GET_WITH_SELECTION(4),
        ACCESS_REQUEST_SET_WITH_SELECTION(5),;

        private int value;

        private Choices(int value) {
            this.value = value;
        }

        public int getValue() {
            return this.value;
        }

        public static Choices valueOf(long tagValue) {
            Choices[] values = Choices.values();

            for (Choices c : values) {
                if (c.value == tagValue) {
                    return c;
                }
            }
            return _ERR_NONE_SELECTED;
        }
    }

    private Choices choice;

    public AccessRequestGet accessRequestGet = null;

    public AccessRequestSet accessRequestSet = null;

    public AccessRequestAction accessRequestAction = null;

    public AccessRequestGetWithSelection accessRequestGetWithSelection = null;

    public AccessRequestSetWithSelection accessRequestSetWithSelection = null;

    public AccessRequestSpecification() {
    }

    public AccessRequestSpecification(byte[] code) {
        this.code = code;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {
        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
            return code.length;

        }
        if (choice == Choices._ERR_NONE_SELECTED) {
            throw new IOException("Error encoding AxdrChoice: No item in choice was selected.");
        }

        int codeLength = 0;

        if (choice == Choices.ACCESS_REQUEST_SET_WITH_SELECTION) {
            codeLength += accessRequestSetWithSelection.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(5);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_GET_WITH_SELECTION) {
            codeLength += accessRequestGetWithSelection.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(4);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_ACTION) {
            codeLength += accessRequestAction.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(3);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_SET) {
            codeLength += accessRequestSet.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(2);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_GET) {
            codeLength += accessRequestGet.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(1);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        // This block should be unreachable
        throw new IOException("Error encoding AxdrChoice: No item in choice was encoded.");
    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;
        AxdrEnum choosen = new AxdrEnum();

        codeLength += choosen.decode(iStream);
        resetChoices();
        this.choice = Choices.valueOf(choosen.getValue());

        if (choice == Choices.ACCESS_REQUEST_GET) {
            accessRequestGet = new AccessRequestGet();
            codeLength += accessRequestGet.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_SET) {
            accessRequestSet = new AccessRequestSet();
            codeLength += accessRequestSet.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_ACTION) {
            accessRequestAction = new AccessRequestAction();
            codeLength += accessRequestAction.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_GET_WITH_SELECTION) {
            accessRequestGetWithSelection = new AccessRequestGetWithSelection();
            codeLength += accessRequestGetWithSelection.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.ACCESS_REQUEST_SET_WITH_SELECTION) {
            accessRequestSetWithSelection = new AccessRequestSetWithSelection();
            codeLength += accessRequestSetWithSelection.decode(iStream);
            return codeLength;
        }

        throw new IOException("Error decoding AxdrChoice: Identifier matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    public Choices getChoiceIndex() {
        return this.choice;
    }

    public void setAccessRequestGet(AccessRequestGet newVal) {
        resetChoices();
        choice = Choices.ACCESS_REQUEST_GET;
        accessRequestGet = newVal;
    }

    public void setAccessRequestSet(AccessRequestSet newVal) {
        resetChoices();
        choice = Choices.ACCESS_REQUEST_SET;
        accessRequestSet = newVal;
    }

    public void setAccessRequestAction(AccessRequestAction newVal) {
        resetChoices();
        choice = Choices.ACCESS_REQUEST_ACTION;
        accessRequestAction = newVal;
    }

    public void setAccessRequestGetWithSelection(AccessRequestGetWithSelection newVal) {
        resetChoices();
        choice = Choices.ACCESS_REQUEST_GET_WITH_SELECTION;
        accessRequestGetWithSelection = newVal;
    }

    public void setAccessRequestSetWithSelection(AccessRequestSetWithSelection newVal) {
        resetChoices();
        choice = Choices.ACCESS_REQUEST_SET_WITH_SELECTION;
        accessRequestSetWithSelection = newVal;
    }

    private void resetChoices() {
        choice = Choices._ERR_NONE_SELECTED;
        accessRequestGet = null;
        accessRequestSet = null;
        accessRequestAction = null;
        accessRequestGetWithSelection = null;
        accessRequestSetWithSelection = null;
    }

    @Override
    public String toString() {
        if (choice == Choices.ACCESS_REQUEST_GET) {
            return "choice: {accessRequestGet: " + accessRequestGet + "}";
        }

        if (choice == Choices.ACCESS_REQUEST_SET) {
            return "choice: {accessRequestSet: " + accessRequestSet + "}";
        }

        if (choice == Choices.ACCESS_REQUEST_ACTION) {
            return "choice: {accessRequestAction: " + accessRequestAction + "}";
        }

        if (choice == Choices.ACCESS_REQUEST_GET_WITH_SELECTION) {
            return "choice: {accessRequestGetWithSelection: " + accessRequestGetWithSelection + "}";
        }

        if (choice == Choices.ACCESS_REQUEST_SET_WITH_SELECTION) {
            return "choice: {accessRequestSetWithSelection: " + accessRequestSetWithSelection + "}";
        }

        return "unknown";
    }

}
