/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;

public class ActionRequestWithFirstPblock implements AxdrType {

    public byte[] code = null;
    public InvokeIdAndPriority invokeIdAndPriority = null;

    public CosemMethodDescriptor cosemMethodDescriptor = null;

    public DataBlockSA pblock = null;

    public ActionRequestWithFirstPblock() {
    }

    public ActionRequestWithFirstPblock(byte[] code) {
        this.code = code;
    }

    public ActionRequestWithFirstPblock(InvokeIdAndPriority invokeIdAndPriority,
            CosemMethodDescriptor cosemMethodDescriptor, DataBlockSA pblock) {
        this.invokeIdAndPriority = invokeIdAndPriority;
        this.cosemMethodDescriptor = cosemMethodDescriptor;
        this.pblock = pblock;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += pblock.encode(axdrOStream);

            codeLength += cosemMethodDescriptor.encode(axdrOStream);

            codeLength += invokeIdAndPriority.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        invokeIdAndPriority = new InvokeIdAndPriority();
        codeLength += invokeIdAndPriority.decode(iStream);

        cosemMethodDescriptor = new CosemMethodDescriptor();
        codeLength += cosemMethodDescriptor.decode(iStream);

        pblock = new DataBlockSA();
        codeLength += pblock.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "invokeIdAndPriority: " + invokeIdAndPriority + ", cosemMethodDescriptor: "
                + cosemMethodDescriptor + ", pblock: " + pblock + "}";
    }

}
