/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class ActionResponseWithList implements AxdrType {

    public static class SubSeqOfListOfResponses extends AxdrSequenceOf<ActionResponseWithOptionalData> {

        @Override
        protected ActionResponseWithOptionalData createListElement() {
            return new ActionResponseWithOptionalData();
        }

        protected SubSeqOfListOfResponses(int length) {
            super(length);
        }

        public SubSeqOfListOfResponses() {
        } // Call empty base constructor

    }

    public byte[] code = null;
    public InvokeIdAndPriority invokeIdAndPriority = null;

    public SubSeqOfListOfResponses listOfResponses = null;

    public ActionResponseWithList() {
    }

    public ActionResponseWithList(byte[] code) {
        this.code = code;
    }

    public ActionResponseWithList(InvokeIdAndPriority invokeIdAndPriority, SubSeqOfListOfResponses listOfResponses) {
        this.invokeIdAndPriority = invokeIdAndPriority;
        this.listOfResponses = listOfResponses;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += listOfResponses.encode(axdrOStream);

            codeLength += invokeIdAndPriority.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        invokeIdAndPriority = new InvokeIdAndPriority();
        codeLength += invokeIdAndPriority.decode(iStream);

        listOfResponses = new SubSeqOfListOfResponses();
        codeLength += listOfResponses.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "invokeIdAndPriority: " + invokeIdAndPriority + ", listOfResponses: " + listOfResponses
                + "}";
    }

}
