/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrOctetString;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrOptional;

public class EventNotificationRequest implements AxdrType {

    public byte[] code = null;
    public AxdrOptional<AxdrOctetString> time = new AxdrOptional<>(new AxdrOctetString(), false);

    public CosemAttributeDescriptor cosemAttributeDescriptor = null;

    public Data attributeValue = null;

    public EventNotificationRequest() {
    }

    public EventNotificationRequest(byte[] code) {
        this.code = code;
    }

    public EventNotificationRequest(AxdrOctetString time, CosemAttributeDescriptor cosemAttributeDescriptor,
            Data attributeValue) {
        this.time.setValue(time);
        this.cosemAttributeDescriptor = cosemAttributeDescriptor;
        this.attributeValue = attributeValue;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += attributeValue.encode(axdrOStream);

            codeLength += cosemAttributeDescriptor.encode(axdrOStream);

            codeLength += time.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        time = new AxdrOptional<>(new AxdrOctetString(), false);
        codeLength += time.decode(iStream);

        cosemAttributeDescriptor = new CosemAttributeDescriptor();
        codeLength += cosemAttributeDescriptor.decode(iStream);

        attributeValue = new Data();
        codeLength += attributeValue.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "time: " + time + ", cosemAttributeDescriptor: " + cosemAttributeDescriptor
                + ", attributeValue: " + attributeValue + "}";
    }

}
