/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class GetRequest implements AxdrType {

    public byte[] code = null;

    public static enum Choices {
        _ERR_NONE_SELECTED(-1),
        GET_REQUEST_NORMAL(1),
        GET_REQUEST_NEXT(2),
        GET_REQUEST_WITH_LIST(3),;

        private int value;

        private Choices(int value) {
            this.value = value;
        }

        public int getValue() {
            return this.value;
        }

        public static Choices valueOf(long tagValue) {
            Choices[] values = Choices.values();

            for (Choices c : values) {
                if (c.value == tagValue) {
                    return c;
                }
            }
            return _ERR_NONE_SELECTED;
        }
    }

    private Choices choice;

    public GetRequestNormal getRequestNormal = null;

    public GetRequestNext getRequestNext = null;

    public GetRequestWithList getRequestWithList = null;

    public GetRequest() {
    }

    public GetRequest(byte[] code) {
        this.code = code;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {
        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
            return code.length;

        }
        if (choice == Choices._ERR_NONE_SELECTED) {
            throw new IOException("Error encoding AxdrChoice: No item in choice was selected.");
        }

        int codeLength = 0;

        if (choice == Choices.GET_REQUEST_WITH_LIST) {
            codeLength += getRequestWithList.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(3);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.GET_REQUEST_NEXT) {
            codeLength += getRequestNext.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(2);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.GET_REQUEST_NORMAL) {
            codeLength += getRequestNormal.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(1);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        // This block should be unreachable
        throw new IOException("Error encoding AxdrChoice: No item in choice was encoded.");
    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;
        AxdrEnum choosen = new AxdrEnum();

        codeLength += choosen.decode(iStream);
        resetChoices();
        this.choice = Choices.valueOf(choosen.getValue());

        if (choice == Choices.GET_REQUEST_NORMAL) {
            getRequestNormal = new GetRequestNormal();
            codeLength += getRequestNormal.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.GET_REQUEST_NEXT) {
            getRequestNext = new GetRequestNext();
            codeLength += getRequestNext.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.GET_REQUEST_WITH_LIST) {
            getRequestWithList = new GetRequestWithList();
            codeLength += getRequestWithList.decode(iStream);
            return codeLength;
        }

        throw new IOException("Error decoding AxdrChoice: Identifier matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    public Choices getChoiceIndex() {
        return this.choice;
    }

    public void setGetRequestNormal(GetRequestNormal newVal) {
        resetChoices();
        choice = Choices.GET_REQUEST_NORMAL;
        getRequestNormal = newVal;
    }

    public void setGetRequestNext(GetRequestNext newVal) {
        resetChoices();
        choice = Choices.GET_REQUEST_NEXT;
        getRequestNext = newVal;
    }

    public void setGetRequestWithList(GetRequestWithList newVal) {
        resetChoices();
        choice = Choices.GET_REQUEST_WITH_LIST;
        getRequestWithList = newVal;
    }

    private void resetChoices() {
        choice = Choices._ERR_NONE_SELECTED;
        getRequestNormal = null;
        getRequestNext = null;
        getRequestWithList = null;
    }

    @Override
    public String toString() {
        if (choice == Choices.GET_REQUEST_NORMAL) {
            return "choice: {getRequestNormal: " + getRequestNormal + "}";
        }

        if (choice == Choices.GET_REQUEST_NEXT) {
            return "choice: {getRequestNext: " + getRequestNext + "}";
        }

        if (choice == Choices.GET_REQUEST_WITH_LIST) {
            return "choice: {getRequestWithList: " + getRequestWithList + "}";
        }

        return "unknown";
    }

}
