/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrBitString;

public class InvokeIdAndPriority extends AxdrBitString {

    public InvokeIdAndPriority() {
        super(8);
    }

    public InvokeIdAndPriority(byte[] bytes) {
        super(bytes);
    }

}
