/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class KekId extends AxdrEnum {

    public KekId() {
        super();
    }

    public KekId(byte[] code) {
        super(code);
    }

    public KekId(long val) {
        super(val);
    }

    public static final int MASTER_KEY = 0;
}
