/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class KeyId extends AxdrEnum {

    public KeyId() {
        super();
    }

    public KeyId(byte[] code) {
        super(code);
    }

    public KeyId(long val) {
        super(val);
    }

    public static final int GLOBAL_UNICAST_ENCRYPTION_KEY = 0;
    public static final int GLOBAL_BROADCAST_ENCRYPTION_KEY = 1;
}
