/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class ListOfAccessRequestSpecification extends AxdrSequenceOf<AccessRequestSpecification> {

    @Override
    protected AccessRequestSpecification createListElement() {
        return new AccessRequestSpecification();
    }

    protected ListOfAccessRequestSpecification(int length) {
        super(length);
    }

    public ListOfAccessRequestSpecification() {
    } // Call empty base constructor

}
