/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class ListOfAccessResponseSpecification extends AxdrSequenceOf<AccessResponseSpecification> {

    @Override
    protected AccessResponseSpecification createListElement() {
        return new AccessResponseSpecification();
    }

    protected ListOfAccessResponseSpecification(int length) {
        super(length);
    }

    public ListOfAccessResponseSpecification() {
    } // Call empty base constructor

}
