/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class ListOfData extends AxdrSequenceOf<Data> {

    @Override
    protected Data createListElement() {
        return new Data();
    }

    protected ListOfData(int length) {
        super(length);
    }

    public ListOfData() {
    } // Call empty base constructor

}
