/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class SetRequestWithList implements AxdrType {

    public static class SubSeqOfAttributeDescriptorList extends AxdrSequenceOf<CosemAttributeDescriptorWithSelection> {

        @Override
        protected CosemAttributeDescriptorWithSelection createListElement() {
            return new CosemAttributeDescriptorWithSelection();
        }

        protected SubSeqOfAttributeDescriptorList(int length) {
            super(length);
        }

        public SubSeqOfAttributeDescriptorList() {
        } // Call empty base constructor

    }

    public static class SubSeqOfValueList extends AxdrSequenceOf<Data> {

        @Override
        protected Data createListElement() {
            return new Data();
        }

        protected SubSeqOfValueList(int length) {
            super(length);
        }

        public SubSeqOfValueList() {
        } // Call empty base constructor

    }

    public byte[] code = null;
    public InvokeIdAndPriority invokeIdAndPriority = null;

    public SubSeqOfAttributeDescriptorList attributeDescriptorList = null;

    public SubSeqOfValueList valueList = null;

    public SetRequestWithList() {
    }

    public SetRequestWithList(byte[] code) {
        this.code = code;
    }

    public SetRequestWithList(InvokeIdAndPriority invokeIdAndPriority,
            SubSeqOfAttributeDescriptorList attributeDescriptorList, SubSeqOfValueList valueList) {
        this.invokeIdAndPriority = invokeIdAndPriority;
        this.attributeDescriptorList = attributeDescriptorList;
        this.valueList = valueList;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += valueList.encode(axdrOStream);

            codeLength += attributeDescriptorList.encode(axdrOStream);

            codeLength += invokeIdAndPriority.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        invokeIdAndPriority = new InvokeIdAndPriority();
        codeLength += invokeIdAndPriority.decode(iStream);

        attributeDescriptorList = new SubSeqOfAttributeDescriptorList();
        codeLength += attributeDescriptorList.decode(iStream);

        valueList = new SubSeqOfValueList();
        codeLength += valueList.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "invokeIdAndPriority: " + invokeIdAndPriority + ", attributeDescriptorList: "
                + attributeDescriptorList + ", valueList: " + valueList + "}";
    }

}
