/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class SetRequest implements AxdrType {

    public byte[] code = null;

    public static enum Choices {
        _ERR_NONE_SELECTED(-1),
        SET_REQUEST_NORMAL(1),
        SET_REQUEST_WITH_FIRST_DATABLOCK(2),
        SET_REQUEST_WITH_DATABLOCK(3),
        SET_REQUEST_WITH_LIST(4),
        SET_REQUEST_WITH_LIST_AND_FIRST_DATABLOCK(5),;

        private int value;

        private Choices(int value) {
            this.value = value;
        }

        public int getValue() {
            return this.value;
        }

        public static Choices valueOf(long tagValue) {
            Choices[] values = Choices.values();

            for (Choices c : values) {
                if (c.value == tagValue) {
                    return c;
                }
            }
            return _ERR_NONE_SELECTED;
        }
    }

    private Choices choice;

    public SetRequestNormal setRequestNormal = null;

    public SetRequestWithFirstDatablock setRequestWithFirstDatablock = null;

    public SetRequestWithDatablock setRequestWithDatablock = null;

    public SetRequestWithList setRequestWithList = null;

    public SetRequestWithListAndFirstDatablock setRequestWithListAndFirstDatablock = null;

    public SetRequest() {
    }

    public SetRequest(byte[] code) {
        this.code = code;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {
        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
            return code.length;

        }
        if (choice == Choices._ERR_NONE_SELECTED) {
            throw new IOException("Error encoding AxdrChoice: No item in choice was selected.");
        }

        int codeLength = 0;

        if (choice == Choices.SET_REQUEST_WITH_LIST_AND_FIRST_DATABLOCK) {
            codeLength += setRequestWithListAndFirstDatablock.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(5);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_LIST) {
            codeLength += setRequestWithList.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(4);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_DATABLOCK) {
            codeLength += setRequestWithDatablock.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(3);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_FIRST_DATABLOCK) {
            codeLength += setRequestWithFirstDatablock.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(2);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_NORMAL) {
            codeLength += setRequestNormal.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(1);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        // This block should be unreachable
        throw new IOException("Error encoding AxdrChoice: No item in choice was encoded.");
    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;
        AxdrEnum choosen = new AxdrEnum();

        codeLength += choosen.decode(iStream);
        resetChoices();
        this.choice = Choices.valueOf(choosen.getValue());

        if (choice == Choices.SET_REQUEST_NORMAL) {
            setRequestNormal = new SetRequestNormal();
            codeLength += setRequestNormal.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_FIRST_DATABLOCK) {
            setRequestWithFirstDatablock = new SetRequestWithFirstDatablock();
            codeLength += setRequestWithFirstDatablock.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_DATABLOCK) {
            setRequestWithDatablock = new SetRequestWithDatablock();
            codeLength += setRequestWithDatablock.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_LIST) {
            setRequestWithList = new SetRequestWithList();
            codeLength += setRequestWithList.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_REQUEST_WITH_LIST_AND_FIRST_DATABLOCK) {
            setRequestWithListAndFirstDatablock = new SetRequestWithListAndFirstDatablock();
            codeLength += setRequestWithListAndFirstDatablock.decode(iStream);
            return codeLength;
        }

        throw new IOException("Error decoding AxdrChoice: Identifier matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    public Choices getChoiceIndex() {
        return this.choice;
    }

    public void setSetRequestNormal(SetRequestNormal newVal) {
        resetChoices();
        choice = Choices.SET_REQUEST_NORMAL;
        setRequestNormal = newVal;
    }

    public void setSetRequestWithFirstDatablock(SetRequestWithFirstDatablock newVal) {
        resetChoices();
        choice = Choices.SET_REQUEST_WITH_FIRST_DATABLOCK;
        setRequestWithFirstDatablock = newVal;
    }

    public void setSetRequestWithDatablock(SetRequestWithDatablock newVal) {
        resetChoices();
        choice = Choices.SET_REQUEST_WITH_DATABLOCK;
        setRequestWithDatablock = newVal;
    }

    public void setSetRequestWithList(SetRequestWithList newVal) {
        resetChoices();
        choice = Choices.SET_REQUEST_WITH_LIST;
        setRequestWithList = newVal;
    }

    public void setSetRequestWithListAndFirstDatablock(SetRequestWithListAndFirstDatablock newVal) {
        resetChoices();
        choice = Choices.SET_REQUEST_WITH_LIST_AND_FIRST_DATABLOCK;
        setRequestWithListAndFirstDatablock = newVal;
    }

    private void resetChoices() {
        choice = Choices._ERR_NONE_SELECTED;
        setRequestNormal = null;
        setRequestWithFirstDatablock = null;
        setRequestWithDatablock = null;
        setRequestWithList = null;
        setRequestWithListAndFirstDatablock = null;
    }

    @Override
    public String toString() {
        if (choice == Choices.SET_REQUEST_NORMAL) {
            return "choice: {setRequestNormal: " + setRequestNormal + "}";
        }

        if (choice == Choices.SET_REQUEST_WITH_FIRST_DATABLOCK) {
            return "choice: {setRequestWithFirstDatablock: " + setRequestWithFirstDatablock + "}";
        }

        if (choice == Choices.SET_REQUEST_WITH_DATABLOCK) {
            return "choice: {setRequestWithDatablock: " + setRequestWithDatablock + "}";
        }

        if (choice == Choices.SET_REQUEST_WITH_LIST) {
            return "choice: {setRequestWithList: " + setRequestWithList + "}";
        }

        if (choice == Choices.SET_REQUEST_WITH_LIST_AND_FIRST_DATABLOCK) {
            return "choice: {setRequestWithListAndFirstDatablock: " + setRequestWithListAndFirstDatablock + "}";
        }

        return "unknown";
    }

}
