/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.ReverseByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrEnum;

public class SetResponse implements AxdrType {

    public byte[] code = null;

    public static enum Choices {
        _ERR_NONE_SELECTED(-1),
        SET_RESPONSE_NORMAL(1),
        SET_RESPONSE_DATABLOCK(2),
        SET_RESPONSE_LAST_DATABLOCK(3),
        SET_RESPONSE_LAST_DATABLOCK_WITH_LIST(4),
        SET_RESPONSE_WITH_LIST(5),;

        private int value;

        private Choices(int value) {
            this.value = value;
        }

        public int getValue() {
            return this.value;
        }

        public static Choices valueOf(long tagValue) {
            Choices[] values = Choices.values();

            for (Choices c : values) {
                if (c.value == tagValue) {
                    return c;
                }
            }
            return _ERR_NONE_SELECTED;
        }
    }

    private Choices choice;

    public SetResponseNormal setResponseNormal = null;

    public SetResponseDatablock setResponseDatablock = null;

    public SetResponseLastDatablock setResponseLastDatablock = null;

    public SetResponseLastDatablockWithList setResponseLastDatablockWithList = null;

    public SetResponseWithList setResponseWithList = null;

    public SetResponse() {
    }

    public SetResponse(byte[] code) {
        this.code = code;
    }

    @Override
    public int encode(ReverseByteArrayOutputStream axdrOStream) throws IOException {
        if (code != null) {
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
            return code.length;

        }
        if (choice == Choices._ERR_NONE_SELECTED) {
            throw new IOException("Error encoding AxdrChoice: No item in choice was selected.");
        }

        int codeLength = 0;

        if (choice == Choices.SET_RESPONSE_WITH_LIST) {
            codeLength += setResponseWithList.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(5);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK_WITH_LIST) {
            codeLength += setResponseLastDatablockWithList.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(4);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK) {
            codeLength += setResponseLastDatablock.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(3);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_DATABLOCK) {
            codeLength += setResponseDatablock.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(2);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_NORMAL) {
            codeLength += setResponseNormal.encode(axdrOStream);
            AxdrEnum c = new AxdrEnum(1);
            codeLength += c.encode(axdrOStream);
            return codeLength;
        }

        // This block should be unreachable
        throw new IOException("Error encoding AxdrChoice: No item in choice was encoded.");
    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;
        AxdrEnum choosen = new AxdrEnum();

        codeLength += choosen.decode(iStream);
        resetChoices();
        this.choice = Choices.valueOf(choosen.getValue());

        if (choice == Choices.SET_RESPONSE_NORMAL) {
            setResponseNormal = new SetResponseNormal();
            codeLength += setResponseNormal.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_DATABLOCK) {
            setResponseDatablock = new SetResponseDatablock();
            codeLength += setResponseDatablock.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK) {
            setResponseLastDatablock = new SetResponseLastDatablock();
            codeLength += setResponseLastDatablock.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK_WITH_LIST) {
            setResponseLastDatablockWithList = new SetResponseLastDatablockWithList();
            codeLength += setResponseLastDatablockWithList.decode(iStream);
            return codeLength;
        }

        if (choice == Choices.SET_RESPONSE_WITH_LIST) {
            setResponseWithList = new SetResponseWithList();
            codeLength += setResponseWithList.decode(iStream);
            return codeLength;
        }

        throw new IOException("Error decoding AxdrChoice: Identifier matched to no item.");
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        ReverseByteArrayOutputStream axdrOStream = new ReverseByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    public Choices getChoiceIndex() {
        return this.choice;
    }

    public void setSetResponseNormal(SetResponseNormal newVal) {
        resetChoices();
        choice = Choices.SET_RESPONSE_NORMAL;
        setResponseNormal = newVal;
    }

    public void setSetResponseDatablock(SetResponseDatablock newVal) {
        resetChoices();
        choice = Choices.SET_RESPONSE_DATABLOCK;
        setResponseDatablock = newVal;
    }

    public void setSetResponseLastDatablock(SetResponseLastDatablock newVal) {
        resetChoices();
        choice = Choices.SET_RESPONSE_LAST_DATABLOCK;
        setResponseLastDatablock = newVal;
    }

    public void setSetResponseLastDatablockWithList(SetResponseLastDatablockWithList newVal) {
        resetChoices();
        choice = Choices.SET_RESPONSE_LAST_DATABLOCK_WITH_LIST;
        setResponseLastDatablockWithList = newVal;
    }

    public void setSetResponseWithList(SetResponseWithList newVal) {
        resetChoices();
        choice = Choices.SET_RESPONSE_WITH_LIST;
        setResponseWithList = newVal;
    }

    private void resetChoices() {
        choice = Choices._ERR_NONE_SELECTED;
        setResponseNormal = null;
        setResponseDatablock = null;
        setResponseLastDatablock = null;
        setResponseLastDatablockWithList = null;
        setResponseWithList = null;
    }

    @Override
    public String toString() {
        if (choice == Choices.SET_RESPONSE_NORMAL) {
            return "choice: {setResponseNormal: " + setResponseNormal + "}";
        }

        if (choice == Choices.SET_RESPONSE_DATABLOCK) {
            return "choice: {setResponseDatablock: " + setResponseDatablock + "}";
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK) {
            return "choice: {setResponseLastDatablock: " + setResponseLastDatablock + "}";
        }

        if (choice == Choices.SET_RESPONSE_LAST_DATABLOCK_WITH_LIST) {
            return "choice: {setResponseLastDatablockWithList: " + setResponseLastDatablockWithList + "}";
        }

        if (choice == Choices.SET_RESPONSE_WITH_LIST) {
            return "choice: {setResponseWithList: " + setResponseWithList + "}";
        }

        return "unknown";
    }

}
