/**
 * This class file was automatically generated by jASN1 v1.10.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerBitString;

public class ACSERequirements extends BerBitString {

    private static final long serialVersionUID = 1L;

    public ACSERequirements() {
    }

    public ACSERequirements(byte[] code) {
        super(code);
    }

    public ACSERequirements(byte[] value, int numBits) {
        super(value, numBits);
    }

    public ACSERequirements(boolean[] value) {
        super(value);
    }

}
