/**
 * This class file was automatically generated by jASN1 v1.10.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import java.math.BigInteger;

import org.openmuc.jasn1.ber.types.BerInteger;

public class AEInvocationIdentifier extends BerInteger {

    private static final long serialVersionUID = 1L;

    public AEInvocationIdentifier() {
    }

    public AEInvocationIdentifier(byte[] code) {
        super(code);
    }

    public AEInvocationIdentifier(BigInteger value) {
        super(value);
    }

    public AEInvocationIdentifier(long value) {
        super(value);
    }

}
