/**
 * This class file was automatically generated by jASN1 v1.10.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerOctetString;

public class APTitleForm2 extends BerOctetString {

    private static final long serialVersionUID = 1L;

    public APTitleForm2() {
    }

    public APTitleForm2(byte[] value) {
        super(value);
    }

}
